LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := rc663nxp
LOCAL_C_INCLUDES := $(LOCAL_PATH)/nxp/intfs
LOCAL_C_INCLUDES += $(LOCAL_PATH)/nxp/types
LOCAL_SRC_FILES := $(shell find nxp -name '*.c')
LOCAL_LDLIBS := -llog
LOCAL_CFLAGS := -DRC663_I2C
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
TARGET_PLATFORM := android-3
LOCAL_MODULE	:= package
LOCAL_SRC_FILES	:= package.c
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := rc663mifare
LOCAL_C_INCLUDES := $(LOCAL_PATH)/nxp/intfs
LOCAL_C_INCLUDES += $(LOCAL_PATH)/nxp/types
LOCAL_SRC_FILES := rc663mifare.c
LOCAL_SHARED_LIBRARIES := rc663nxp
LOCAL_SHARED_LIBRARIES += package
LOCAL_LDLIBS := -llog
LOCAL_CFLAGS := -DRC663_I2C
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := rc663_15693
LOCAL_C_INCLUDES := $(LOCAL_PATH)/nxp/intfs
LOCAL_C_INCLUDES += $(LOCAL_PATH)/nxp/types
LOCAL_SRC_FILES := rc663_15693.c
LOCAL_SHARED_LIBRARIES := rc663nxp
LOCAL_SHARED_LIBRARIES += package
LOCAL_LDLIBS := -llog
LOCAL_CFLAGS := -DRC663_I2C
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := rc663_2ndGID
LOCAL_C_INCLUDES := $(LOCAL_PATH)/nxp/intfs
LOCAL_C_INCLUDES += $(LOCAL_PATH)/nxp/types
LOCAL_SRC_FILES := rc663_2ndGID.c
LOCAL_SHARED_LIBRARIES := rc663nxp
LOCAL_SHARED_LIBRARIES += package
LOCAL_LDLIBS := -llog
LOCAL_CFLAGS := -DRC663_I2C
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := rc663ultraght
LOCAL_C_INCLUDES := $(LOCAL_PATH)/nxp/intfs
LOCAL_C_INCLUDES += $(LOCAL_PATH)/nxp/types
LOCAL_SRC_FILES := ultralight.c
LOCAL_SHARED_LIBRARIES := rc663nxp
LOCAL_SHARED_LIBRARIES += package
LOCAL_LDLIBS := -llog
LOCAL_CFLAGS := -DRC663_I2C
include $(BUILD_SHARED_LIBRARY)
